.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "ANON\-CONNECTION\-WIZARD" "8" "April 2020" "anon-connection-wizard" "anon-connection-wizard Manual"
.SH "NAME"
\fBanon\-connection\-wizard\fR \- Anonimity Distribution Connection Wizard
.P
.SH "SYNOPSIS"
anon\-connection\-wizard
.SH "DESCRIPTION"
anon\-connection\-wizard is a Tor\-launcher\-like application that helps users in different Internet environment connect to the Tor network\. It helps user to configure Tor to use a proxy and/or Tor bridges\. This application is especially useful for system Tor users who would like to run the standalone core Tor with different torified applications\. The wizard can be run at any time to change the connection configuration\.
.P
anon\-connection\-wizard is produced independently from the Tor anonymity software and carries no guarantee from The Tor Project about quality, suitability or anything else\.
.SH "WWW"
https://www\.whonix\.org
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@riseup\.net) and Iry (iry@riseup\.net)\.
