#!/usr/bin/python3 -u

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

from subprocess import call
import sys, os
import time
import shutil

anon_connection_wizard = shutil.which("anon-connection-wizard")
if anon_connection_wizard == None:
    print('ERROR: anon-connection-wizard not found! Exiting.')
    sys.exit(1)

command = 'xhost +local:root'
call(command, shell = True)

command = 'kdesudo {}'.format(anon_connection_wizard)
call(command, shell=True)
