#!/usr/bin/python3 -u

## This file is part of Whonix.
## Copyright (C) 2012 - 2018 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

from subprocess import call
import sys, os
import time
import distutils.spawn

command = 'xhost +local:root'
call(command, shell = True)

anon_connection_wizard = distutils.spawn.find_executable("anon-connection-wizard")
if not anon_connection_wizard == "":
    command = 'kdesudo {} setup'.format(anon_connection_wizard)
    call(command, shell=True)
